# For more info on HTTP files go to https://aka.ms/vs/httpfile

### Getting all issues

GET http://localhost:1338/issues

### Get requests by status


GET http://localhost:1338/issues?status=Tacos

### Get just a single issue

GET http://localhost:1338/issues/71984ba-f562-4d2f-ae51-ff21cd48f2ff

### Adding a new Issue

POST http://localhost:1338/issues
Content-Type: application/json

{
  "description": "Getting Hungry",
  "application": "The Angular Application",
  "contactEmail": "jeff@x.z"
}