services:
  db:
    image: postgres:15.2-bullseye
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: db
    ports:
      - 5432:5432
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d/
      - db_data:/var/lib/postgresql/data
  business-clock-api:
    image: jeffrygonzalez/clock-api-bsd-aug-2023:latest
    ports:
      - 1337:80
    environment:
      TZ: "America/New_York"
      ASPNETCORE_ENVIRONMENT: "Development"
volumes:
  db_data: